#!/bin/sh

KEYSTORE=/home/adq/data/kindle.keystore
JAR=kif.azw2
MANIFEST=kif.manifest

jar cfm $JAR $MANIFEST -C bin .
jarsigner -keystore $KEYSTORE -storepass password $JAR dkadq
jarsigner -keystore $KEYSTORE -storepass password $JAR diadq
jarsigner -keystore $KEYSTORE -storepass password $JAR dnadq
