#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys

if len(sys.argv) != 5:
    print >>sys.stderr, "Syntax: bincompare <filename1> <file1offset> <filename2> <file2offset>"
    sys.exit(1)

filename1 = sys.argv[1]
fileoffset1 = int(sys.argv[2], 0)
filename2 = sys.argv[3]
fileoffset2 = int(sys.argv[4], 0)

file1 = open(filename1, "rb")
file2 = open(filename2, "rb")

file1.seek(fileoffset1)
file2.seek(fileoffset2)

offset = 0
while True:
    val1 = ord(file1.read(1))
    val2 = ord(file2.read(1))
    
    if (val1 != val2):
        print "%08x: %02x %02x" % (offset, val1, val2)
        
    offset += 1
  